### PR TITLE
use SafeTestsets.jl

### LINKED ISSUE #197: Warning in test suite - use SafeTestsets.jl
## Describe the bug
There's a warning in the test suite:

https://github.com/CliMA/ClimaLSM.jl/actions/runs/4984091932/jobs/8921970519#step:6:439

I recommend we start using https://github.com/YingboMa/SafeTestsets.jl to ensure tests are leaking data/information across unit tests.

Edit: Addressed by PR #322

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
Use SafeTestsets to prevent leaking data between tests. This PR also moves some tests for soil BC calculations from `test/standalone/Soil/soiltest.jl` to `test/standalone/Soil/soil_bc.jl`, which I think is a more logical place for them to live.

Closes #197 

## Content
- [x] wrap all tests in `test/runtests.jl` in `@safetestset`
- [x] move soil BC calculation tests

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -1,27 +1,98 @@
...
-include("integrated/soil_energy_hydrology_biogeochemistry.jl")
-include("standalone/Soil/climate_drivers.jl")
-include("standalone/Soil/soil_test_3d.jl")
-include("standalone/Soil/soiltest.jl")
-include("standalone/Soil/soil_parameterizations.jl")
-include("standalone/Soil/soil_bc.jl")
-include("standalone/Soil/runoff.jl")
+using SafeTestsets
+
+# Performance and code quality tests
```
Comment (kmdeck) [inline test/runtests.jl:3]: nice restructuring of this file and clear comments! :)

**Review by kmdeck — APPROVED** [review]
looks good, thank you for implementing this!
