### PR TITLE
restore Float32 compatibility

### LINKED ISSUE #327: Cannot run simulations with Float32
## Describe the bug
In ClimaTimesteppers, the float type of the time `t` is Float64. In several places, we require the type of the time variable and the underlying type of the state vectors to be the same. We need to relax this. We also need to change functions where we prescribed driving data as a function of time, so that whatever is returned is converted to the right type.

Close https://github.com/CliMA/ClimaLSM.jl/issues/229 at the same time

See https://github.com/CliMA/ClimaCoupler.jl/issues/396 for discussion with more details

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
fixes #327, #229

### Notes
- code extending tests to cover Float32 and Float64 is on branch js/float32-tests - will need to cherry pick these changes onto this branch
  - tests won't pass until other changes are made (`t::FT` and `eltype(t)`) - make those changes first
- idea: it may be helpful to add a flag that checks that our t_start/dt/t_end/FT setup won't exceed the FT's precision - if it does, give warning to user

## To-do
- [x] remove `t::FT` type annotations
- [x] remove `eltype(t)(...)` usage
  - ex https://github.com/CliMA/ClimaLSM.jl/blob/main/docs/tutorials/Bucket/bucket_tutorial.jl#L229-L230
  - in tests, this can be replaced by `FT(...)`
  - [x] functions of time that return `eltype(t)(result)` --> instead convert to FT where function called from
  - [x] boundary conditions, PrescribedAtmosphere, PrescribedRadiativeFluxes, canopy prescribed soil moisture, canopy transpiration
- [x] make sure tests cover Float64 and Float32
- [ ] make sure simulations try Float64 and Float32 - this will be a separate PR #384
  - idea: loop over `(FT, t_end)`, run Float32 only for a couple steps. At end of sim, if statement for FT which tests final type for both and makes plots for Float64
  - alt idea: loop over `FT`, run `solve` for Float64 and `step` for Float32. At end of sim, if statement for FT which tests final type for both and makes plots for Float64
- [x] add documentation for how to maintain Float32 and Float64 compatibility (in [wiki](https://github.com/CliMA/ClimaLSM.jl/wiki/Floating-point-precision-issues))

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by juliasloan25** [comment]
bors cancel

File: src/integrated/pond_soil_model.jl [hunk 1]
```diff
@@ -238,9 +243,9 @@ struct RunoffBC <: Soil.AbstractSoilBC end
         ::TopBoundary,
         Δz::FT,
         p::NamedTuple,
-        t::FT,
+        t,
         params,
-    )::ClimaCore.Fields.Field where {FT}
```
Comment (juliasloan25) [inline src/integrated/pond_soil_model.jl:243]: this should still have `where {FT}`

File: docs/tutorials/Usage/LSM_single_column_tutorial.jl [hunk 2]
```diff
@@ -173,9 +173,9 @@ soil_ode! = make_exp_tendency(soil);
 # them inside our pond model, since again, the pond model structure
 # must contain everything needed to make the tendency function:
 
-precipitation(t::T) where {T} = t < T(20) ? -T(1e-5) : T(0.0) # m/s
```
Comment (juliasloan25) [inline docs/tutorials/Usage/LSM_single_column_tutorial.jl:176]: remove `FT()` from these functions, apply where functions are called instead

File: src/standalone/Soil/boundary_conditions.jl [hunk 3]
```diff
@@ -259,14 +263,15 @@ function ClimaLSM.boundary_flux(
     p::NamedTuple,
     t,
 )::ClimaCore.Fields.Field
+    FT = eltype(Y)
```
Comment (juliasloan25) [inline src/standalone/Soil/boundary_conditions.jl:266]: use eltype(dz) instead

Comment (juliasloan25) [reply src/standalone/Soil/boundary_conditions.jl:266]: same on line 303

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl [hunk 4]
```diff
@@ -121,24 +126,23 @@ lat = FT(38.7441) # degree
...
-    FT(
-        instantaneous_zenith_angle(
-            dt,
-            orbital_data,
-            longitude,
-            latitude,
-            insol_params,
-        )[1],
-    )
+    # TODO do we need to wrap this in FT? can we get FT from a param other than t?
```
Comment (juliasloan25) [inline experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:138]: remove comment, get FT from orbital_data?

File: src/shared_utilities/drivers.jl [hunk 5]
```diff
@@ -81,9 +84,12 @@ struct PrescribedAtmosphere{FT, LP, SP, TA, UA, QA, RA, CA, DT} <:
         args = (liquid_precip, snow_precip, T, u, q, P, c_co2, ref_time)
         return new{typeof(h), typeof.(args)...}(args..., h, gustiness)
     end
-
 end
 
+float_type(
```
Comment (juliasloan25) [inline src/shared_utilities/drivers.jl:89]: I added these `float_type` functions but didn't actually end up using them, so I think I'll remove them

File: docs/tutorials/Bucket/bucket_tutorial.jl [hunk 6]
```diff
@@ -390,7 +390,7 @@ plot(
     ylabel = "T_sfc (K)",
     legend = :bottomright,
 )
-plot!(sol.t ./ 86400, T_atmos.(sol.t), label = "Atmospheric Temperature")
+plot!(sol.t ./ 86400, FT.(T_atmos.(sol.t)), label = "Atmospheric Temperature")
```
Comment (kmdeck) [inline docs/tutorials/Bucket/bucket_tutorial.jl:393]: do we need to convert to FT to plot?

File: docs/tutorials/Canopy/canopy_tutorial.jl [hunk 7]
```diff
@@ -114,11 +114,11 @@ shared_params = SharedCanopyParameters{FT, typeof(earth_param_set)}(
 
 ψ_soil0 = FT(0.0)
 
-soil_driver = PrescribedSoil(
-    root_depths = FT.(-Array(10:-1:1.0) ./ 10.0 * 2.0 .+ 0.2 / 2.0),
-    ψ_soil = t -> eltype(t)(ψ_soil0),
-    soil_α_PAR = FT(0.2),
-    soil_α_NIR = FT(0.4),
+soil_driver = PrescribedSoil{FT}(
+    FT.(-Array(10:-1:1.0) ./ 10.0 * 2.0 .+ 0.2 / 2.0), # root_depths
```
Comment (kmdeck) [inline docs/tutorials/Canopy/canopy_tutorial.jl:118]: out of curiosity, do we need these FTs in the arguments?

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl [hunk 8]
```diff
@@ -99,8 +99,13 @@ atmos_u = Spline1D(seconds, WS[:])
 LW_IN_spline = Spline1D(seconds, LW_IN[:])
 SW_IN_spline = Spline1D(seconds, SW_IN[:])
 atmos_h = FT(32)
-precipitation_function(t::FT) where {FT} = p_spline(t) < 0.0 ? p_spline(t) : 0.0 # m/s
-snow_precip(t) = eltype(t)(0) # this is likely not correct
+
+function precipitation_function(t)
```
Comment (kmdeck) [inline experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:103]: Im not sure we need this. the eltype of the spline is Float64, so I dont think this gains us anything over using eltype of t?

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 4 above)
Comment (kmdeck) [inline experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:138]: can we pass FT as a keyword argument after it is defined (closure)?

it may be stored in the orbital data also

File: experiments/integrated/ozark/soil_retention_curve.jl [hunk 9]
```diff
@@ -16,12 +16,13 @@ swrc_data = readdlm(data, ','; skipstart = 1)
...
 ψ = swrc_data[4:end, 2] .* 1e6 ./ (1e3 * 9.8) # to convert from MPa to m
 
+FT = Float64
 # Assume value for this:
 θ_r = 0.04
 α = 10.0 .^ (log10(5e-3):0.1:1)
 n = Array(1.1:0.05:3.0)
 porosity = [0.45, 0.5, 0.55]
-L2 = zeros(Float64, (length(α), length(n)))
+L2 = zeros(FT, (length(α), length(n)))
```
Comment (kmdeck) [inline experiments/integrated/ozark/soil_retention_curve.jl:25]: I dont think we need these changes really, this is a one off file for fitting parameters but isnt ever used in the simulation.

File: src/standalone/Vegetation/soil_drivers.jl [hunk 10]
```diff
@@ -31,12 +31,12 @@ end
...
      ) where {FT}
 
-An outer constructor for the PrescribedSoil soil driver allowing the user to 
+An outer constructor for the PrescribedSoil soil driver allowing the user to
 specify the soil parameters by keyword arguments.
 """
 function PrescribedSoil(;
     root_depths::Vector{FT} = FT.(-Array(10:-1:1.0) ./ 10.0 * 2.0 .+ 0.2 / 2.0),
-    ψ_soil::Function = t -> eltype(t)(FT(0.0)),
+    ψ_soil::Function = t -> 0.0,
```
Comment (kmdeck) [inline src/standalone/Vegetation/soil_drivers.jl:39]: might as well return FT(0)?

File: src/standalone/Vegetation/PlantHydraulics.jl [hunk 11]
```diff
@@ -521,12 +521,13 @@ To prevent dividing by zero, we change AI/(AI x dz)" to
 """
 function make_compute_exp_tendency(model::PlantHydraulicsModel, canopy)
     function compute_exp_tendency!(dY, Y, p, t)
+        FT = eltype(p.canopy.hydraulics.area_index.root)
```
Comment (kmdeck) [inline src/standalone/Vegetation/PlantHydraulics.jl:524]: in cases like this, should we get FT from the model (or another struct) instead? it seems a little cleaner to me.

File: src/standalone/Vegetation/PlantHydraulics.jl [hunk 12]
```diff
@@ -591,8 +592,8 @@ function root_flux_per_ground_area!(
     model::PlantHydraulicsModel{FT},
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
-) where {FT}
+    t,
+) where {FT <: AbstractFloat}
```
Comment (kmdeck) [inline src/standalone/Vegetation/PlantHydraulics.jl:596]: I dont know that we need to enforce this here, because FT <: AbstractFloat is part of the definition of AbstractCanopyComponent{FT}: https://github.com/CliMA/ClimaLSM.jl/blob/ad31773009c9309d5e45b083603873a8914be286/src/standalone/Vegetation/component_models.jl#L21

File: src/standalone/Vegetation/PlantHydraulics.jl [hunk 13]
```diff
@@ -669,9 +670,9 @@ function transpiration_per_ground_area(
     transpiration::PrescribedTranspiration{FT},
     _,
     _,
-    t::FT,
-)::FT where {FT}
-    return transpiration.T(t) # (m/s)
+    t,
+)::FT where {FT <: AbstractFloat}
+    return FT(transpiration.T(t)) # (m/s)
```
Comment (kmdeck) [inline src/standalone/Vegetation/PlantHydraulics.jl:675]: I think we are also OK here without saying FT<:AbstractFloat (and just "FT"), because of https://github.com/CliMA/ClimaLSM.jl/blob/ad31773009c9309d5e45b083603873a8914be286/src/standalone/Vegetation/PlantHydraulics.jl#L54

File: src/standalone/Vegetation/radiation.jl [hunk 14]
```diff
@@ -174,11 +174,11 @@ for a radiative transfer model.
...
 """
 function compute_NIR(
-    model::AbstractRadiationModel,
+    model::AbstractRadiationModel{FT},
     solar_radiation::ClimaLSM.PrescribedRadiativeFluxes,
     t,
-)
-    return solar_radiation.SW_d(t) / 2
+) where {FT <: AbstractFloat}
+    return FT(solar_radiation.SW_d(t) / 2)
```
Comment (kmdeck) [inline src/standalone/Vegetation/radiation.jl:181]: likewise here

File: src/standalone/Vegetation/Canopy.jl [hunk 15]
```diff
@@ -636,8 +636,8 @@ function canopy_surface_fluxes(
     model::CanopyModel,
     Y,
     p,
-    t::FT,
-) where {FT}
+    t,
+) where {FT <: AbstractFloat}
```
Comment (kmdeck) [inline src/standalone/Vegetation/Canopy.jl:640]: also here: https://github.com/CliMA/ClimaLSM.jl/blob/ad31773009c9309d5e45b083603873a8914be286/src/shared_utilities/drivers.jl#L27, no need for <: AbstractFloat

File: src/standalone/Soil/rre.jl [hunk 16]
```diff
@@ -168,9 +168,9 @@ Construct the tendency computation function for the explicit terms of the RHS,
 which are horizontal components and source/sink terms.
 """
 function ClimaLSM.make_compute_exp_tendency(model::Soil.RichardsModel)
-    function compute_exp_tendency!(dY, Y, p, t::FT) where {FT}
+    function compute_exp_tendency!(dY, Y, p, t)
```
Comment (kmdeck) [inline src/standalone/Soil/rre.jl:171]: do we want to get FT from the RichardModel struct?

Comment (kmdeck) [reply src/standalone/Soil/rre.jl:171]: this is fine the way you have it also though, only needed in one spot.

File: src/standalone/Soil/energy_hydrology.jl [hunk 17]
```diff
@@ -563,14 +563,13 @@ because the surface air density is not a prognostic
...
-    atmos::PrescribedAtmosphere{FT},
+    atmos::PrescribedAtmosphere{FT, CA, DT},
     model::EnergyHydrology{FT},
     Y,
     p,
     t,
     T_sfc,
-) where {FT}
-
+) where {FT <: AbstractFloat, CA, DT}
```
Comment (kmdeck) [inline src/standalone/Soil/energy_hydrology.jl:572]: do we also need to pass in CA, DT?

dont need <: AbstractFloat

File: src/standalone/Soil/boundary_conditions.jl [hunk 18]
```diff
@@ -259,14 +263,15 @@ function ClimaLSM.boundary_flux(
     p::NamedTuple,
     t,
 )::ClimaCore.Fields.Field
+    FT = eltype(Δz)
```
Comment (kmdeck) [inline src/standalone/Soil/boundary_conditions.jl:266]: This is totally fine, but Im wondering if it is easier to get FT from the parametric type of the BC or if that cleaner or if there is no preference.

File: src/standalone/Soil/boundary_conditions.jl [hunk 19]
```diff
@@ -203,7 +206,8 @@ function ClimaLSM.boundary_flux(
     p::NamedTuple,
     t,
 )::ClimaCore.Fields.Field
-    return bc.bc(p, t) .+ ClimaCore.Fields.zeros(axes(Δz))
+    FT = eltype(Δz)
+    return FT.(bc.bc(p, t)) .+ ClimaCore.Fields.zeros(axes(Δz))
```
Comment (kmdeck) [inline src/standalone/Soil/boundary_conditions.jl:210]: do we need this here? or will it get converted appropriately since it is added to a Field with (presumably) a fixed type?

File: src/standalone/Soil/boundary_conditions.jl [hunk 20]
```diff
@@ -155,24 +155,27 @@ presence of a canopy, snow, etc, as in a land surface model,
...
+        <:PrescribedRadiativeFluxes{FT, DT2, T, OD},
+    },
     boundary::ClimaLSM.TopBoundary,
     model::EnergyHydrology{FT},
     Δz,
     Y,
     p,
     t,
-) where {FT}
+) where {FT <: AbstractFloat, CA, DT1, DT2, T, OD}
```
Comment (kmdeck) [inline src/standalone/Soil/boundary_conditions.jl:173]: Let's remove the extra types since they are not used. same comment re <: AbstractFloat

File: src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl [hunk 21]
```diff
@@ -431,9 +449,9 @@ function ClimaLSM.boundary_flux(
     Δz::ClimaCore.Fields.Field,
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
-)::ClimaCore.Fields.Field where {FT}
-    return bc.bc(p, t) .+ ClimaCore.Fields.zeros(axes(Δz))
+    t,
+)::ClimaCore.Fields.Field
+    return FT.(bc.bc(p, t)) .+ ClimaCore.Fields.zeros(axes(Δz))
```
Comment (kmdeck) [inline src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl:454]: same ?: do we need to convert to FT here, since it is added to a Field of (fixed) type? It might be converted automatically.

File: src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl [hunk 22]
```diff
@@ -467,12 +485,13 @@ function ClimaLSM.boundary_flux(
     Δz::ClimaCore.Fields.Field,
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
-)::ClimaCore.Fields.Field where {FT}
+    t,
+)::ClimaCore.Fields.Field
+    FT = eltype(Δz)
```
Comment (kmdeck) [inline src/standalone/Soil/Biogeochemistry/Biogeochemistry.jl:490]: I think my pref is to get FT from the BC type. but we can discuss! otherwise Im not sure the BC's need to have a parametric type at all.

we could also make clear in the BC docs (future PR) that FT is used to convert functions of time into the right type, or something.

File: src/standalone/Snow/Snow.jl [hunk 23]
```diff
@@ -30,13 +30,13 @@ struct SnowParameters{FT <: AbstractFloat, PSE}
     "Thermal conductivity of ice (W/m/K)"
     κ_ice::FT
     "Timestep of the model"
-    Δt::FT
+    Δt::Any
```
Comment (kmdeck) [inline src/standalone/Snow/Snow.jl:33]: do we need to even pass in a type if it is Any? What does it gain us?

File: src/standalone/Snow/Snow.jl [hunk 24]
```diff
@@ -63,7 +63,7 @@ function SnowParameters{FT}(
     fS_c = FT(0.2),
     κ_ice = FT(2.21),
     earth_param_set::PSE,
-) where {FT, PSE}
+) where {FT <: AbstractFloat, PSE}
```
Comment (kmdeck) [inline src/standalone/Snow/Snow.jl:66]: not sure we need the FT <: AbstractFloat here? https://github.com/CliMA/ClimaLSM.jl/blob/ad31773009c9309d5e45b083603873a8914be286/src/standalone/Snow/Snow.jl#L13

File: src/standalone/Bucket/bucket_parameterizations.jl [hunk 25]
```diff
@@ -55,21 +55,21 @@ a helper function which computes and returns the surface air density for the buc
...
 function ClimaLSM.surface_air_density(
-    atmos::PrescribedAtmosphere,
+    atmos::PrescribedAtmosphere{FT, CA, DT},
     model::BucketModel,
     Y,
     p,
     t,
     T_sfc,
-)
+) where {FT <: AbstractFloat, CA, DT}
```
Comment (kmdeck) [inline src/standalone/Bucket/bucket_parameterizations.jl:64]: what does {CA, DT} gain us?

File: src/standalone/Bucket/Bucket.jl [hunk 26]
```diff
@@ -156,11 +156,11 @@ should be used.
 function BulkAlbedoTemporal{FT}(
     regrid_dirpath::String,
     date_ref::Union{DateTime, DateTimeNoLeap},
-    t_start::FT,
+    t_start,
     space::ClimaCore.Spaces.AbstractSpace;
     infile_path = Bucket.cesm2_albedo_dataset_path(),
     varname = "sw_alb",
-) where {FT}
+) where {FT <: AbstractFloat}
```
Comment (kmdeck) [inline src/standalone/Bucket/Bucket.jl:163]: do we need this? or is FT already defined to be a subtype of AbstractFloat somewhere else (defn of BulkAlbedoTemporal?)

File: src/shared_utilities/utils.jl [hunk 27]
```diff
@@ -85,16 +85,12 @@ end
...
 
 Computes the weighted direct stiffness summation and updates `Y` in place.
 In the case of a column domain, no dss operations are performed.
 """
-function dss!(
-    Y::ClimaCore.Fields.FieldVector{FT},
-    p::NamedTuple,
-    t::FT,
-) where {FT}
+function dss!(Y::ClimaCore.Fields.FieldVector{FT}, p::NamedTuple, t) where {FT}
```
Comment (kmdeck) [inline src/shared_utilities/utils.jl:93]: the root of it all 😅

File: src/shared_utilities/drivers.jl [hunk 28]
```diff
@@ -324,17 +333,25 @@ end
...
 
 """
     snow_precipitation(atmos::PrescribedAtmosphere, p, t)
 
 Returns the precipitation in snow (m of liquid water/s) at the surface.
 """
-function snow_precipitation(atmos::PrescribedAtmosphere, p, t)
-    return atmos.snow_precip(t)
+function snow_precipitation(
+    atmos::PrescribedAtmosphere{FT, CA, DT},
```
Comment (kmdeck) [inline src/shared_utilities/drivers.jl:350]: same comment here as down below

File: src/shared_utilities/drivers.jl [hunk 29]
```diff
@@ -303,7 +312,7 @@ function net_radiation(
     model::AbstractModel{FT},
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
+    t,
 ) where {FT <: AbstractFloat}
```
Comment (kmdeck) [inline src/shared_utilities/drivers.jl:316]: same comment here as down below

File: src/shared_utilities/drivers.jl [hunk 30]
```diff
@@ -147,12 +149,12 @@ It solves for these given atmospheric conditions, stored in `atmos`,
...
 function surface_fluxes(
-    atmos::PrescribedAtmosphere{FT},
+    atmos::PrescribedAtmosphere{FT, CA, DT},
     model::AbstractModel{FT},
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
-) where {FT <: AbstractFloat}
+    t,
+) where {FT <: AbstractFloat, CA, DT}
```
Comment (kmdeck) [inline src/shared_utilities/drivers.jl:157]: same comment here as down below

File: docs/tutorials/Bucket/bucket_tutorial.jl (hunk 6 above)
Comment (juliasloan25) [reply docs/tutorials/Bucket/bucket_tutorial.jl:393]: probably not! I can remove these

File: docs/tutorials/Canopy/canopy_tutorial.jl (hunk 7 above)
Comment (juliasloan25) [reply docs/tutorials/Canopy/canopy_tutorial.jl:118]: I wanted to enforce that they'll all be FT, but I think it's sufficient to pass FT as a type argument to `PrescribedSoil`, so I can remove it for the individual arguments

File: experiments/integrated/ozark/conservation/ozark_conservation.jl [hunk 31]
```diff
@@ -264,7 +264,7 @@ root_sink = [sum(-1 .* sv.saveval[k].root_extraction) for k in 2:length(sol.t)]
 # Free Drainage BC, F_bot = -K_bot
 soil_bottom_flux = [-parent(sv.saveval[k].soil.K)[1] for k in 2:length(sol.t)]
 # Precip is not stored in the aux state, evaluated using sol.t
-precip = [atmos.liquid_precip.(sol.t[k]) for k in 1:(length(sol.t) - 1)]
+precip = [FT.(atmos.liquid_precip.(sol.t[k])) for k in 1:(length(sol.t) - 1)]
```
[the remark this answers is not in the document]
Comment (juliasloan25) [reply experiments/integrated/ozark/conservation/ozark_conservation.jl:267]: good catch! I'll remove it

File: experiments/integrated/ozark/soil_retention_curve.jl (hunk 9 above)
Comment (juliasloan25) [reply experiments/integrated/ozark/soil_retention_curve.jl:25]: okay, I'll remove them

File: src/standalone/Snow/Snow.jl (hunk 23 above)
Comment (juliasloan25) [reply src/standalone/Snow/Snow.jl:33]: We don't, but for some reason the formatter keeps adding this... I'll try to remove it again

File: docs/tutorials/Canopy/canopy_tutorial.jl (hunk 7 above)
Comment (juliasloan25) [reply docs/tutorials/Canopy/canopy_tutorial.jl:118]: btw, there are some places in main where we do this currently (like [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/docs/tutorials/Canopy/canopy_tutorial.jl#L127-L137)), but I think it's okay to have a mix of approaches and leave it out here

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 4 above)
Comment (juliasloan25) [reply experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:138]: I don't think I understand - how would we use a closure to get FT?

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 8 above)
Comment (juliasloan25) [reply experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:103]: You're right, we can remove it since we wrap the value in FT after it's returned

File: src/standalone/Vegetation/PlantHydraulics.jl (hunk 11 above)
Comment (juliasloan25) [reply src/standalone/Vegetation/PlantHydraulics.jl:524]: sure! I'll change this to get FT from the model and try to find other instances like this

File: src/standalone/Soil/boundary_conditions.jl (hunk 18 above)
Comment (juliasloan25) [reply src/standalone/Soil/boundary_conditions.jl:266]: I don't think we're storing FT in the BC (code [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/standalone/Soil/boundary_conditions.jl#L14)). We could add it as a type parameter for BCs, but I think using dz is easier

File: src/standalone/Soil/boundary_conditions.jl (hunk 19 above)
Comment (juliasloan25) [reply src/standalone/Soil/boundary_conditions.jl:210]: good point! I think it will get converted

File: src/standalone/Snow/Snow.jl (hunk 23 above)
Comment (juliasloan25) [reply src/standalone/Snow/Snow.jl:33]: Yeah, the formatter just adds it back if I try to remove it :/

File: src/standalone/Bucket/bucket_parameterizations.jl (hunk 25 above)
Comment (juliasloan25) [reply src/standalone/Bucket/bucket_parameterizations.jl:64]: I don't think we need them, I'll remove them

File: src/standalone/Vegetation/PlantHydraulics.jl (hunk 12 above)
Comment (juliasloan25) [reply src/standalone/Vegetation/PlantHydraulics.jl:596]: Ahh good point, I'll remove all the `<: AbstractFloat`s

File: src/shared_utilities/FileReader.jl [hunk 32]
```diff
@@ -154,15 +154,15 @@ end
...
+    PrescribedDataTemporal{FT}(
         regrid_dirpath,
         infile_path,
         varname,
         date_ref,
         t_start,
         surface_space;
         mono = true,
-    )
+    ) where {FT <: AbstractFloat}
```
Comment (juliasloan25) [inline src/shared_utilities/FileReader.jl:165]: I realized that I'm passing `FT` to these external `PrescribedDataTemporal` constructors, but `PrescribedDataTemporal` itself doesn't actually have `FT` as a parametric type, and so doesn't constrain `FT <: AbstractFloat`. Maybe I should add `FT as a type parameter for it? @kmdeck

File: docs/tutorials/Canopy/canopy_tutorial.jl (hunk 7 above)
Comment (kmdeck) [reply docs/tutorials/Canopy/canopy_tutorial.jl]: ok! and good to keep in mind. as I come across those, Ill remove them as long as they dont clutter PR diffs!

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 4 above)
Comment (kmdeck) [reply experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:137]: hm, I guess I thought this would be a closure
```
FT = Float64
function foo(a, b; FT = FT)
 # use FT
end
```
and then pass foo into the model. But, maybe that isnt a closure. 

I think we can get FT from the insol params too :)

File: src/standalone/Soil/boundary_conditions.jl (hunk 18 above)
Comment (kmdeck) [reply src/standalone/Soil/boundary_conditions.jl:265]: good point!

File: src/standalone/Snow/Snow.jl (hunk 23 above)
Comment (kmdeck) [reply src/standalone/Snow/Snow.jl:33]: hahah, the formatter is being creative

File: src/integrated/soil_canopy_model.jl [hunk 33]
```diff
@@ -395,18 +394,18 @@ function PlantHydraulics.root_flux_per_ground_area!(
     model::Canopy.PlantHydraulics.PlantHydraulicsModel{FT},
     Y::ClimaCore.Fields.FieldVector,
     p::NamedTuple,
-    t::FT,
-) where {FT}
+    t,
+) where {(FT)}
```
Comment (kmdeck) [inline src/integrated/soil_canopy_model.jl:398]: parentheses?

Comment (kmdeck) [reply src/integrated/soil_canopy_model.jl:398]: do you think it is good practice to not use the `where {FT}`/include parameteric types if we arent dispatching off them/dont need the FT in the function?

not to change in this PR. more a question for the future

File: src/shared_utilities/FileReader.jl (hunk 32 above)
Comment (kmdeck) [reply src/shared_utilities/FileReader.jl:165]: hmmm that makes sense to me! if FT is needed in setting up the data from it or anything, having it handy in the type would be useful. and when we set up the simulation we pick the float type and can set it consistently. we can also possibly enforce that this FT is the same as the model FT...possibly in the model constructor? not sure

File: src/shared_utilities/drivers.jl [hunk 34]
```diff
@@ -240,24 +242,27 @@ function surface_fluxes_at_a_point(
...
 
 """
-    PrescribedRadiativeFluxes{FT, SW, LW, DT, T, OD} <: AbstractRadiativeDrivers{FT}
+    PrescribedRadiativeFluxes{FT, DT, T, OD} <: AbstractRadiativeDrivers{FT}
 
 Container for the prescribed radiation functions needed to drive land models in standalone mode.
 $(DocStringExtensions.FIELDS)
+
+The arguments labeled with "function of time" are typically either of type
+`Function` or type `Spline1D` from the `Dierckx.jl` package.
```
Comment (kmdeck) [inline src/shared_utilities/drivers.jl:265]: thanks for clarifying this!

File: src/shared_utilities/utils.jl (hunk 27 above)
Comment (kmdeck) [inline src/shared_utilities/utils.jl:93]: this should be fine! but seeing this reminded me of this https://github.com/CliMA/ClimaLSM.jl/issues/356 (which we need to fix anyways, but which made me thing that right now our FieldVectors are not always with parametric type {FT}.

FT can be anything here, so it doesnt affect things, but also FT isnt used in the function. maybe here we can just get rid of it?

File: src/standalone/Soil/boundary_conditions.jl (hunk 18 above)
Comment (kmdeck) [reply src/standalone/Soil/boundary_conditions.jl:265]: oh - whatever you think is best is fine - but I just noticed that we have FT available in the model also, and that is an argument.

File: src/standalone/Vegetation/PlantHydraulics.jl [hunk 35]
```diff
@@ -142,8 +142,8 @@ function PlantHydraulicsParameters(;
 ) where {FT}
     return PlantHydraulicsParameters{
         FT,
-        typeof(conductivity_model),
-        typeof(retention_model),
+        Base.typeof(conductivity_model),
```
Comment (kmdeck) [inline src/standalone/Vegetation/PlantHydraulics.jl:145]: do we need Base. here?

File: test/shared_utilities/variable_types.jl [hunk 36]
```diff
@@ -17,97 +17,99 @@ using ClimaLSM.Domains: HybridBox, Column, Point
...
-
-    dm_compute_imp_tendency! = make_compute_imp_tendency(dm)
-    @test dm_compute_imp_tendency!(x[1], x[2], x[3], x[4]) == nothing
-    @test x == [0, 1, 2, 3]
-
-    dm_update_aux! = make_update_aux(dm)
-    @test dm_update_aux!(x[1], x[2], x[3]) == nothing
-    @test x == [0, 1, 2, 3]
-end
+for FT in (Float32, Float64)
```
Comment (kmdeck) [inline test/shared_utilities/variable_types.jl:20]: Im not sure we need the different values of FT for this test? (I know it doesnt really make a difference and is good practice. but not sure if we want to be a little more judicious about where we test multiple types, since doing everywhere will double CI time (I think?))

**Review by kmdeck — APPROVED** [review]
Julia - thanks much for taking on this mammoth task! I left a couple other comments that are small, and had a question about if we needed the FT loop for all of our tests. Otherwise I think it is good to go once CI passes :)

**Comment by kmdeck** [comment]
@Espeer5 @AlexisRenchon it might be good to take a look at this PR and see the broad type of change @juliasloan25  is making, as well as take a look at the docs she has written https://github.com/CliMA/ClimaLSM.jl/wiki/Floating-point-precision-issues. To make her life easier with this PR, let's try and make any new PRs (vaira experiment, other experiments, heterotrophic respiration), respect the changes made here. The overarching idea is that we cannot rely on `t` being the same type as the FT we use for the state, parameters, model, etc. It will always be Float64.

e.g. avoid using `t::FT`, `(p,t) -> eltype(t)(value)`

**Comment by AlexisRenchon** [comment]
is this PR far from being merged? 
if it will be merged soon we could wait for it before we merge ours. (and when we do, we'll avoid `eltype` etc.)

**Comment by kmdeck** [comment]
> is this PR far from being merged? if it will be merged soon we could wait for it before we merge ours. (and when we do, we'll avoid `eltype` etc.)

I think Julia will merge this pretty quickly once she is back, but I dont think that is until next week.

**Comment by AlexisRenchon** [comment]
I'm ok to wait, this is a big PR

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 4 above)
Comment (kmdeck) [reply experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:137]: This works:
```
function zenith_angle(
    t,
    orbital_data,
    ref_time;
    latitude = lat,
    longitude = long,
    insol_params::Insolation.Parameters.InsolationParameters{FT} = earth_param_set.insol_params,
) where {FT}
    # This should be time in UTC
    dt = ref_time + Dates.Second(round(t))
    # Orbital Data uses Float64, so we need to convert to our sim
    # FT.
    FT(
        instantaneous_zenith_angle(
            dt,
            orbital_data,
            longitude,
            latitude,
            insol_params,
        )[1],
    )
end

```

Ill change to this for the Ozark and Vaira site runs (PR adding the Vaira site), we can change next week when youre back if you prefer a different approach!

File: test/shared_utilities/variable_types.jl (hunk 36 above)
Comment (juliasloan25) [reply test/shared_utilities/variable_types.jl:20]: I agree, I don't think we need both FTs for this test. On one hand, it might be good practice to cover both FTs everywhere, and I don't think it will quite double CI time since precompilation still just happens once. I'm okay with either covering both FTs in all tests, or doing it for just the ones we think require it (maybe in the latter case we could add a note justifying why we don't need to cover both FTs)

File: experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl (hunk 4 above)
Comment (juliasloan25) [reply experiments/integrated/ozark/ozark_met_drivers_FLUXNET.jl:137]: Looks good, thank you!

File: src/shared_utilities/FileReader.jl (hunk 32 above)
Comment (juliasloan25) [reply src/shared_utilities/FileReader.jl:165]: I feel conflicted... FT would only be used in interpolation, I think ([here](https://github.com/CliMA/ClimaLSM.jl/blob/10e457ad9e6930b90181924f8bddd6b33ae446c5/src/shared_utilities/FileReader.jl#L390-L412)). I think it's fine to continue getting FT from the space as we do now, and maybe simpler

File: src/integrated/soil_canopy_model.jl (hunk 33 above)
Comment (juliasloan25) [reply src/integrated/soil_canopy_model.jl:398]: I'm not sure - I don't think we get any quantitative benefit from specifying `where {FT}` in these cases, but maybe it's a bit more readable/clear to the user? I'm fine with either way

File: test/shared_utilities/variable_types.jl (hunk 36 above)
Comment (kmdeck) [reply test/shared_utilities/variable_types.jl:20]: I think my preference would be to only do where required but it's your call! youre right that it wont double CI.

File: src/integrated/soil_canopy_model.jl (hunk 33 above)
Comment (kmdeck) [reply src/integrated/soil_canopy_model.jl:398]: ok! maybe this is something we can clean up as we merge PRs that affect these functions if we decide to do this. I can see both sides :) but might lean towards removing (might be confusing to newer users of Julia?).
